name: Build and Release

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  # cross compile for some other platforms, like arm, mips, etc.
  cross-compile:
    runs-on: ubuntu-latest
    container: "ubuntu:20.04"
    strategy:
      fail-fast: false
      matrix:
        cross_host: [x86_64-linux-musl]
        arch: [znver2]
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /usr/src/
            /var/cache/apt/
          key: cross-build-dependencies-cache-${{ matrix.cross_host }}-${{ github.sha }}
          restore-keys: |
            cross-build-dependencies-cache-${{ matrix.cross_host }}-
      - name: cross compile nox-static
        env:
          CROSS_HOST: "${{ matrix.cross_host }}"
          MTUNE_ARCH: "${{ matrix.arch }}"
        run: .github/workflows/cross_build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: qbittorrent-enhanced-nox_${{ matrix.cross_host }}_${{ matrix.arch }}_static
          path: |
            /tmp/qbittorrent-nox*
      - name: Upload Github Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ".github/workflows/qbittorrent-enhanced-nox_${{ matrix.cross_host }}_${{ matrix.arch }}_static.zip"
          tag: ${{ github.ref }}
          overwrite: true
